galaxy_info:
  author: adgs9876543
  description: Configuración de nodos Slurm para cluster académico.
  company: Universidad
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - hpc
    - slurm
    - cluster
dependencies: []
